### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by daminals** [SamAsh11414/MathYouDidntNeed#1]
You should make a version in TI-Basic so that you could port it to your TI-84

**Comment by SamAsh11414** [comment]
Good idea, time to learn TI-basic

**Comment by daminals** [comment]
I remember I used to have a RadDeg program in TI-Basic but I forgot to back it up before resetting my calculator. Here are some of the programs I did save though if you want to take a look https://github.com/daminals/TI-BASIC

**Comment by daminals** [comment]
What I love about TI-Basic is that it's so simple and unifocused that in order to make a good program to calculate something you have to spend a lot of time understanding the steps of that thing and figuring out how to convert them to basic commands. The best online tool for coding in basic is Cemetech (https://www.cemetech.net), but what I used to do is just do it during math class on my calculator directly, or whenever I had free time to procrastinate math homework

**Comment by SamAsh11414** [comment]
I'll def check those out
